<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 69,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 70,
                'data_type_id' => 8,
                'field' => 'nombre_completo',
                'type' => 'text',
                'display_name' => 'Nombre Completo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6},"validation":{"rule":"required|max:100","messages":{"required":"El campo :attribute es requerido.","max":"EL campo :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 71,
                'data_type_id' => 8,
                'field' => 'ci',
                'type' => 'text',
                'display_name' => 'CI',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6},"validation":{"rule":"required|max:20","messages":{"required":"El campo :attribute es requerido.","max":"EL campo :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 3,
            ),
            3 => 
            array (
                'id' => 72,
                'data_type_id' => 8,
                'field' => 'rau',
                'type' => 'text',
                'display_name' => 'RAU',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6},"validation":{"rule":"required|max:50","messages":{"required":"El campo :attribute es requerido.","max":"EL campo :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 4,
            ),
            4 => 
            array (
                'id' => 73,
                'data_type_id' => 8,
                'field' => 'movil',
                'type' => 'text',
                'display_name' => 'Telefono/Movil',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6},"validation":{"rule":"required|max:10","messages":{"required":"El campo :attribute es requerido.","max":"EL campo :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 5,
            ),
            5 => 
            array (
                'id' => 74,
                'data_type_id' => 8,
                'field' => 'direccion',
                'type' => 'text_area',
                'display_name' => 'Dirección',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            6 => 
            array (
                'id' => 75,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            7 => 
            array (
                'id' => 76,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            8 => 
            array (
                'id' => 77,
                'data_type_id' => 8,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            9 => 
            array (
                'id' => 78,
                'data_type_id' => 7,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            10 => 
            array (
                'id' => 79,
                'data_type_id' => 7,
                'field' => 'nombre',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:100","messages":{"required":"El campo :attribute es requerido.","max":"EL campo :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 2,
            ),
            11 => 
            array (
                'id' => 80,
                'data_type_id' => 7,
                'field' => 'tipo',
                'type' => 'select_dropdown',
                'display_name' => 'Tipo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6},"default":"ingreso","options":{"ingreso":"Ingreso","egreso":"Egreso"}}',
                'order' => 3,
            ),
            12 => 
            array (
                'id' => 81,
                'data_type_id' => 7,
                'field' => 'monto',
                'type' => 'text',
                'display_name' => 'Monto',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6},"validation":{"rule":"required|max:100","messages":{"required":"El campo :attribute es requerido.","max":"EL campo :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 4,
            ),
            13 => 
            array (
                'id' => 82,
                'data_type_id' => 7,
                'field' => 'descripcion',
                'type' => 'text_area',
                'display_name' => 'Descripción',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            14 => 
            array (
                'id' => 83,
                'data_type_id' => 7,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            15 => 
            array (
                'id' => 84,
                'data_type_id' => 7,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            16 => 
            array (
                'id' => 85,
                'data_type_id' => 7,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            17 => 
            array (
                'id' => 86,
                'data_type_id' => 6,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            18 => 
            array (
                'id' => 87,
                'data_type_id' => 6,
                'field' => 'nombre',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:100","messages":{"required":"El campo :attribute es requerido.","max":"EL campo :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 2,
            ),
            19 => 
            array (
                'id' => 88,
                'data_type_id' => 6,
                'field' => 'tipo',
                'type' => 'select_dropdown',
                'display_name' => 'Tipo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"monto","options":{"monto":"Monto fijo","porcentaje":"Porcentaje"}}',
                'order' => 3,
            ),
            20 => 
            array (
                'id' => 89,
                'data_type_id' => 6,
                'field' => 'detalles',
                'type' => 'text_area',
                'display_name' => 'Detalles',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            21 => 
            array (
                'id' => 90,
                'data_type_id' => 6,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            22 => 
            array (
                'id' => 91,
                'data_type_id' => 6,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            23 => 
            array (
                'id' => 92,
                'data_type_id' => 6,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
        ));
        
        
    }
}