<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 69,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 70,
                'data_type_id' => 8,
                'field' => 'nombre_completo',
                'type' => 'text',
                'display_name' => 'Nombre Completo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6},"validation":{"rule":"required|max:100","messages":{"required":"El campo :attribute es requerido.","max":"EL campo :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 71,
                'data_type_id' => 8,
                'field' => 'ci',
                'type' => 'text',
                'display_name' => 'CI',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6},"validation":{"rule":"required|max:20","messages":{"required":"El campo :attribute es requerido.","max":"EL campo :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 3,
            ),
            3 => 
            array (
                'id' => 72,
                'data_type_id' => 8,
                'field' => 'rau',
                'type' => 'text',
                'display_name' => 'RAU',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6},"validation":{"rule":"max:50","messages":{"required":"El campo :attribute es requerido."}}}',
                'order' => 4,
            ),
            4 => 
            array (
                'id' => 73,
                'data_type_id' => 8,
                'field' => 'movil',
                'type' => 'text',
                'display_name' => 'Telefono/Movil',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6},"validation":{"rule":"required|max:10","messages":{"required":"El campo :attribute es requerido.","max":"EL campo :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 5,
            ),
            5 => 
            array (
                'id' => 74,
                'data_type_id' => 8,
                'field' => 'direccion',
                'type' => 'text_area',
                'display_name' => 'Dirección',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            6 => 
            array (
                'id' => 75,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            7 => 
            array (
                'id' => 76,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            8 => 
            array (
                'id' => 77,
                'data_type_id' => 8,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            9 => 
            array (
                'id' => 78,
                'data_type_id' => 7,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            10 => 
            array (
                'id' => 79,
                'data_type_id' => 7,
                'field' => 'nombre',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:100","messages":{"required":"El campo :attribute es requerido.","max":"EL campo :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 4,
            ),
            11 => 
            array (
                'id' => 81,
                'data_type_id' => 7,
                'field' => 'monto',
                'type' => 'number',
                'display_name' => 'Monto',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6},"validation":{"rule":"required|max:100","messages":{"required":"El campo :attribute es requerido.","max":"EL campo :attribute debe tener :max caracteres como m\\u00e1ximo."}},"step":0.01,"min":0}',
                'order' => 6,
            ),
            12 => 
            array (
                'id' => 82,
                'data_type_id' => 7,
                'field' => 'descripcion',
                'type' => 'text_area',
                'display_name' => 'Descripción',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            13 => 
            array (
                'id' => 83,
                'data_type_id' => 7,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            14 => 
            array (
                'id' => 84,
                'data_type_id' => 7,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            15 => 
            array (
                'id' => 85,
                'data_type_id' => 7,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            16 => 
            array (
                'id' => 86,
                'data_type_id' => 6,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            17 => 
            array (
                'id' => 87,
                'data_type_id' => 6,
                'field' => 'nombre',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|max:100","messages":{"required":"El campo :attribute es requerido.","max":"EL campo :attribute debe tener :max caracteres como m\\u00e1ximo."}}}',
                'order' => 2,
            ),
            18 => 
            array (
                'id' => 89,
                'data_type_id' => 6,
                'field' => 'detalles',
                'type' => 'text_area',
                'display_name' => 'Detalles',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            19 => 
            array (
                'id' => 90,
                'data_type_id' => 6,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            20 => 
            array (
                'id' => 91,
                'data_type_id' => 6,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            21 => 
            array (
                'id' => 92,
                'data_type_id' => 6,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            22 => 
            array (
                'id' => 93,
                'data_type_id' => 7,
                'field' => 'cuenta_id',
                'type' => 'text',
                'display_name' => 'Cuenta',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            23 => 
            array (
                'id' => 94,
                'data_type_id' => 7,
                'field' => 'aporte_belongsto_cuenta_relationship',
                'type' => 'relationship',
                'display_name' => 'cuentas',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Cuenta","table":"cuentas","type":"belongsTo","column":"cuenta_id","key":"id","label":"nombre","pivot_table":"afiliados","pivot":"0","taggable":"0"}',
                'order' => 3,
            ),
            24 => 
            array (
                'id' => 95,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            25 => 
            array (
                'id' => 96,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            26 => 
            array (
                'id' => 97,
                'data_type_id' => 3,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            27 => 
            array (
                'id' => 98,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            28 => 
            array (
                'id' => 99,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            29 => 
            array (
                'id' => 100,
                'data_type_id' => 7,
                'field' => 'tipo',
                'type' => 'select_dropdown',
                'display_name' => 'Tipo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6},"default":"monto","options":{"monto":"Monto fijo","porcentaje":"Porcentaje"}}',
                'order' => 5,
            ),
            30 => 
            array (
                'id' => 101,
                'data_type_id' => 8,
                'field' => 'localidad',
                'type' => 'text',
                'display_name' => 'Localidad',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"max:191","messages":{"required":"El campo :attribute es requerido."}}}',
                'order' => 6,
            ),
            31 => 
            array (
                'id' => 102,
                'data_type_id' => 8,
                'field' => 'fecha_afiliacion',
                'type' => 'date',
                'display_name' => 'Fecha Afiliación',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6},"validation":{"rule":"required","messages":{"required":"El campo :attribute es requerido."}}}',
                'order' => 8,
            ),
            32 => 
            array (
                'id' => 103,
                'data_type_id' => 8,
                'field' => 'foto',
                'type' => 'image',
                'display_name' => 'Fotografía',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6},"resize":{"width":"512","height":null},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"256","height":"256"}}]}',
                'order' => 9,
            ),
            33 => 
            array (
                'id' => 104,
                'data_type_id' => 1,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            34 => 
            array (
                'id' => 105,
                'data_type_id' => 1,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Role Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            35 => 
            array (
                'id' => 106,
                'data_type_id' => 1,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            36 => 
            array (
                'id' => 107,
                'data_type_id' => 1,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            37 => 
            array (
                'id' => 108,
                'data_type_id' => 1,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            38 => 
            array (
                'id' => 109,
                'data_type_id' => 1,
                'field' => 'email_verified_at',
                'type' => 'timestamp',
                'display_name' => 'Email Verified At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            39 => 
            array (
                'id' => 110,
                'data_type_id' => 1,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Password',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            40 => 
            array (
                'id' => 111,
                'data_type_id' => 1,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Remember Token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            41 => 
            array (
                'id' => 112,
                'data_type_id' => 1,
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            42 => 
            array (
                'id' => 113,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            43 => 
            array (
                'id' => 114,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            44 => 
            array (
                'id' => 115,
                'data_type_id' => 1,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Rol',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"afiliados","pivot":"0","taggable":"0"}',
                'order' => 11,
            ),
            45 => 
            array (
                'id' => 116,
                'data_type_id' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Roles',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'order' => 12,
            ),
            46 => 
            array (
                'id' => 117,
                'data_type_id' => 9,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            47 => 
            array (
                'id' => 122,
                'data_type_id' => 9,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":4}}',
                'order' => 4,
            ),
            48 => 
            array (
                'id' => 123,
                'data_type_id' => 9,
                'field' => 'debe',
                'type' => 'text',
                'display_name' => 'Debe',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"display":{"width":2}}',
                'order' => 8,
            ),
            49 => 
            array (
                'id' => 124,
                'data_type_id' => 9,
                'field' => 'haber',
                'type' => 'text',
                'display_name' => 'Haber',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"display":{"width":2}}',
                'order' => 9,
            ),
            50 => 
            array (
                'id' => 125,
                'data_type_id' => 9,
                'field' => 'tipo',
                'type' => 'select_dropdown',
                'display_name' => 'Tipo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"A","options":{"A":"Activo","P":"Pasivo-Patrimonio","G":"Gasto"},"display":{"width":3}}',
                'order' => 10,
            ),
            51 => 
            array (
                'id' => 126,
                'data_type_id' => 9,
                'field' => 'grupo',
                'type' => 'select_dropdown',
                'display_name' => 'Grupo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"1","options":{"1":"Balance","2":"E. G. y P Naturaleza","3":"E. G. y P Funcion"},"display":{"width":3}}',
                'order' => 11,
            ),
            52 => 
            array (
                'id' => 127,
                'data_type_id' => 9,
                'field' => 'conasev',
                'type' => 'text',
                'display_name' => 'Conasev',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"display":{"width":3}}',
                'order' => 12,
            ),
            53 => 
            array (
                'id' => 128,
                'data_type_id' => 9,
                'field' => 'saldo',
                'type' => 'text',
                'display_name' => 'Saldo',
                'required' => 0,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"display":{"width":3}}',
                'order' => 13,
            ),
            54 => 
            array (
                'id' => 129,
                'data_type_id' => 9,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 14,
            ),
            55 => 
            array (
                'id' => 130,
                'data_type_id' => 9,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 15,
            ),
            56 => 
            array (
                'id' => 131,
                'data_type_id' => 9,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 16,
            ),
            57 => 
            array (
                'id' => 132,
                'data_type_id' => 9,
                'field' => 'element',
                'type' => 'select_dropdown',
                'display_name' => 'Element',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"ACTIVO DISPONIBLE Y EXIGIBLE","options":{"ACTIVO DISPONIBLE Y EXIGIBLE":"ACTIVO DISPONIBLE Y EXIGIBLE","ACTIVO REALIZABLE":"ACTIVO REALIZABLE","ACTIVO INMOVILIZADO":"ACTIVO INMOVILIZADO","PASIVO":"PASIVO","PATRIMONIO NETO":"PATRIMONIO NETO"," GASTOS POR NATURALEZA":" GASTOS POR NATURALEZA","INGRESOS":"INGRESOS","SALDOS INTERMEDIARIOS DE GESTI\\u00d3N Y DETERMINACI\\u00d3N DE LOS RESULTADOS DEL EJERCICIO":"SALDOS INTERMEDIARIOS DE GESTI\\u00d3N Y DETERMINACI\\u00d3N DE LOS RESULTADOS DEL EJERCICIO","CONTABILIDAD ANAL\\u00cdTICA DE EXPLOTACI\\u00d3N":"CONTABILIDAD ANAL\\u00cdTICA DE EXPLOTACI\\u00d3N"}}',
                'order' => 2,
            ),
            58 => 
            array (
                'id' => 133,
                'data_type_id' => 9,
                'field' => 'code',
                'type' => 'text',
                'display_name' => 'Codigo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":2}}',
                'order' => 3,
            ),
            59 => 
            array (
                'id' => 134,
                'data_type_id' => 10,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            60 => 
            array (
                'id' => 135,
                'data_type_id' => 10,
                'field' => 'code',
                'type' => 'text',
                'display_name' => 'Codigo',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6}}',
                'order' => 2,
            ),
            61 => 
            array (
                'id' => 136,
                'data_type_id' => 10,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6}}',
                'order' => 3,
            ),
            62 => 
            array (
                'id' => 137,
                'data_type_id' => 10,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            63 => 
            array (
                'id' => 138,
                'data_type_id' => 10,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            64 => 
            array (
                'id' => 139,
                'data_type_id' => 10,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
        ));
        
        
    }
}